#ifndef RAAANDROIDNETWORK_GLOBAL_H
#define RAAANDROIDNETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RAAANDROIDNETWORK_LIBRARY)
#  define RAAANDROIDNETWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RAAANDROIDNETWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RAAANDROIDNETWORK_GLOBAL_H
